import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PanelBottom } from "lucide-react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "トップ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="flex flex-col min-h-screen">
        <header className="p-4 bg-gray-200 text-left">
          <h1>My Memo App</h1>
          <Link href="/memos">一覧ページへ</Link>
        </header>

        <main className="flex-grow flex items-center justify-center">
          {children}
        </main>

        <footer className="p-4 bg-gray-200 text-left">
          <p>@ 2025 My Meomo APP</p>
        </footer>
      </body>
    </html>
  );
}
